### ISSUE TITLE
Error on beta11 and zone.js 0.6.4

### ISSUE THREAD

**Issue by mburger81** [akserg/ng2-dnd#5] opened 2016-03-23 16:08 UTC
There seems to be errors on beta 11 and zone.js 0.6.4

![image](https://cloud.githubusercontent.com/assets/3778892/13991812/d2b76aa0-f119-11e5-9322-b71ef48cab7a.png)

**Comment by AndrewLosikhin** [comment] 2016-03-30 09:29
+1

**Comment by akserg** [comment] 2016-03-30 16:24
I'm busy fixing your problem now.

**Comment by akserg** [comment] 2016-03-31 07:17
I have updated library to Angular 2.0.0-beta.12. Can you check and confirm that the issue was fixed. 
If not, please provide following information:
- browser info
- source code snippet where this one was happens.

**Comment by AndrewLosikhin** [comment] 2016-03-31 10:36
It's caused by angular2 bug. The workaround for know is using synchronous event emitters e.g.

```
@Output("onDragSuccess") onDragSuccessCallback: EventEmitter<any> = new EventEmitter<any>(false);

    @Output("onDragStart") onDragStartCallback: EventEmitter<any> = new EventEmitter<any>(false);
    @Output("onDragOver") onDragOverCallback: EventEmitter<any> = new EventEmitter<any>(false);
    @Output("onDragEnd") onDragEndCallback: EventEmitter<any> = new EventEmitter<any>(false);
    @Output("onDropSuccess") onDropSuccessCallback: EventEmitter<any> = new EventEmitter<any>(false);
```

**Comment by akserg** [comment] 2016-03-31 15:01
I seen this issue not in examples nor in online demo:
- [ng2-systemjs-demo](https://github.com/akserg/ng2-systemjs-demo)
- [ng2-webpack-demo](https://github.com/akserg/ng2-webpack-demo)
- [here](http://akserg.github.io/ng2-webpack-demo)

**Comment by akserg** [comment] 2016-04-02 09:00
I have updated the library to Angular 2.0.0-beta.13.

**Comment by akserg** [comment] 2016-04-04 05:46
I'm closing this issue. Please reopen if you steel have an issue.

**Closed by akserg** 2016-04-04 05:46 UTC
